package mathematics.topology;

import mathematics.core.MathFailure;
import mathematics.foundations.FiniteSet;
import mathematics.linear.IntegerMatrix;
import mathematics.linear.IntegerSmithNormalForm.Computation;
import mathematics.structures.*;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.*;

/** A labelled pair (X,A), with relative integral chains freely generated by simplices of X outside A. */
public final class RelativeSimplicialComplex implements Serializable {
    private static final long serialVersionUID=1L;
    public static final int MAX_SIMPLICES=4096;
    private final FiniteSimplicialComplex ambient,subcomplex;
    public RelativeSimplicialComplex(FiniteSimplicialComplex ambient,FiniteSimplicialComplex subcomplex) {
        this.ambient=Objects.requireNonNull(ambient); this.subcomplex=Objects.requireNonNull(subcomplex);
        if(ambient.faces().size()>MAX_SIMPLICES || subcomplex.faces().size()>MAX_SIMPLICES)
            throw new MathFailure(MathFailure.Kind.IMPLEMENTATION_FAILURE,"Relative complexes allow at most 4096 nonempty simplices per complex");
        if(!subcomplex.subcomplexOf(ambient)) throw MathFailure.undefined("A relative pair requires a labelled subcomplex of its ambient complex");
    }
    public static RelativeSimplicialComplex absolute(FiniteSimplicialComplex complex) {
        return new RelativeSimplicialComplex(complex,new FiniteSimplicialComplex(Collections.emptyList()));
    }
    public static RelativeSimplicialComplex diagonal(FiniteSimplicialComplex complex) { return new RelativeSimplicialComplex(complex,complex); }
    public FiniteSimplicialComplex ambient() { return ambient; }
    public FiniteSimplicialComplex subcomplex() { return subcomplex; }
    public FiniteSimplicialMap inclusion() { return FiniteSimplicialMap.inclusion(subcomplex,ambient); }
    public int dimension() {
        int result=-1; for(FiniteSet<Integer> simplex : ambient.faces()) if(!subcomplex.faces().contains(simplex)) result=Math.max(result,simplex.size()-1); return result;
    }
    public BigInteger eulerCharacteristic() { return ambient.eulerCharacteristic().subtract(subcomplex.eulerCharacteristic()); }
    private static void requireDegree(BigInteger degree) { if(degree.signum()<0) throw MathFailure.undefined("Relative chain degree must be nonnegative"); }
    private static List<FiniteSet<Integer>> basis(FiniteSimplicialComplex complex,FiniteSimplicialComplex omit,BigInteger degree) {
        if(degree.signum()<0 || degree.compareTo(BigInteger.valueOf(complex.dimension()))>0) return Collections.emptyList();
        return IntegralSimplicialHomology.orderedBasis(complex,omit,degree.intValueExact());
    }
    List<FiniteSet<Integer>> basis(BigInteger degree) { return basis(ambient,subcomplex,degree); }
    public int simplexCount(BigInteger degree) { requireDegree(degree); return basis(degree).size(); }
    public List<FiniteSet<BigInteger>> simplexBasis(BigInteger degree) {
        requireDegree(degree); List<FiniteSet<BigInteger>> result=new ArrayList<>();
        for(FiniteSet<Integer> simplex : basis(degree)) {
            List<BigInteger> labels=new ArrayList<>(); for(int vertex : IntegralSimplicialHomology.vertices(simplex)) labels.add(BigInteger.valueOf(vertex));
            result.add(new FiniteSet<>(labels));
        }
        return Collections.unmodifiableList(result);
    }
    private static BigInteger[][] zeros(int rows,int columns,Computation work) {
        work.use((long)rows*columns); BigInteger[][] entries=new BigInteger[rows][columns];
        for(BigInteger[] row : entries) Arrays.fill(row,BigInteger.ZERO); return entries;
    }
    private static Map<FiniteSet<Integer>,Integer> positions(List<FiniteSet<Integer>> basis) {
        Map<FiniteSet<Integer>,Integer> result=new HashMap<>(); for(int i=0;i<basis.size();i++) result.put(basis.get(i),i); return result;
    }
    /** Retain only oriented faces occurring in the selected row basis. */
    static IntegerMatrix boundary(List<FiniteSet<Integer>> rows,List<FiniteSet<Integer>> columns,Computation work) {
        BigInteger[][] entries=zeros(rows.size(),columns.size(),work); Map<FiniteSet<Integer>,Integer> index=positions(rows);
        for(int c=0;c<columns.size();c++) {
            List<Integer> simplex=IntegralSimplicialHomology.vertices(columns.get(c)); work.use((long)simplex.size()*simplex.size());
            for(int i=0;i<simplex.size();i++) {
                List<Integer> face=new ArrayList<>(simplex); face.remove(i); Integer row=index.get(new FiniteSet<>(face));
                if(row!=null) entries[row][c]=(i&1)==0?BigInteger.ONE:BigInteger.ONE.negate();
            }
        }
        return new IntegerMatrix(rows.size(),columns.size(),entries);
    }
    static IntegerMatrix selector(List<FiniteSet<Integer>> rows,List<FiniteSet<Integer>> columns,Computation work) {
        BigInteger[][] entries=zeros(rows.size(),columns.size(),work); Map<FiniteSet<Integer>,Integer> index=positions(rows);
        for(int c=0;c<columns.size();c++) { Integer row=index.get(columns.get(c)); if(row!=null) entries[row][c]=BigInteger.ONE; }
        return new IntegerMatrix(rows.size(),columns.size(),entries);
    }
    public IntegerMatrix boundaryMatrix(BigInteger degree) { requireDegree(degree); return boundaryMatrix(degree,new Computation()); }
    IntegerMatrix boundaryMatrix(BigInteger degree,Computation work) { return boundary(basis(degree.subtract(BigInteger.ONE)),basis(degree),work); }
    public List<IntegerMatrix> boundaryMatrices() {
        Computation work=new Computation(); List<IntegerMatrix> result=new ArrayList<>();
        for(int k=0;k<=ambient.dimension();k++) result.add(boundaryMatrix(BigInteger.valueOf(k),work)); return Collections.unmodifiableList(result);
    }
    public IntegralHomology homology(BigInteger degree) { requireDegree(degree); return homology(degree,new Computation()); }
    IntegralHomology homology(BigInteger degree,Computation work) {
        requireDegree(degree);
        return new IntegralHomology(boundaryMatrix(degree,work),boundaryMatrix(degree.add(BigInteger.ONE),work),work);
    }
    public List<IntegralHomology> homologyDegrees() {
        Computation work=new Computation(); List<IntegralHomology> result=new ArrayList<>();
        for(int k=0;k<=ambient.dimension();k++) result.add(homology(BigInteger.valueOf(k),work)); return Collections.unmodifiableList(result);
    }
    public AbelianGroupType homologyType(BigInteger degree) { return homology(degree).type(); }
    public List<AbelianGroupType> homologyTypes() {
        List<AbelianGroupType> result=new ArrayList<>(); for(IntegralHomology degree : homologyDegrees()) result.add(degree.type()); return Collections.unmodifiableList(result);
    }
    public IntegerMatrix projectionMatrix(BigInteger degree) { requireDegree(degree); return projectionMatrix(degree,new Computation()); }
    IntegerMatrix projectionMatrix(BigInteger degree,Computation work) { return selector(basis(degree),basis(ambient,null,degree),work); }
    /** The canonical zero-on-A lift is a chain-group section, generally not a chain map. */
    public IntegerMatrix liftMatrix(BigInteger degree) { return projectionMatrix(degree).transpose(); }
    public IntegerMatrix inclusionMatrix(BigInteger degree) { requireDegree(degree); return inclusionMatrix(degree,new Computation()); }
    IntegerMatrix inclusionMatrix(BigInteger degree,Computation work) { return selector(basis(ambient,null,degree),basis(subcomplex,null,degree),work); }
    /** A-component of the boundary of a zero-on-A lift; only relative cycles necessarily give cycles in A. */
    public IntegerMatrix connectingChainMatrix(BigInteger degree) { requireDegree(degree); return connectingChainMatrix(degree,new Computation()); }
    IntegerMatrix connectingChainMatrix(BigInteger degree,Computation work) {
        return boundary(basis(subcomplex,null,degree.subtract(BigInteger.ONE)),basis(degree),work);
    }
    private IntegralHomology connectingTarget(BigInteger degree,Computation work) {
        return degree.signum()==0?new IntegralHomology(IntegerMatrix.zero(0,0),IntegerMatrix.zero(0,0),work)
                :IntegralHomology.atDegree(subcomplex,degree.subtract(BigInteger.ONE),work);
    }
    public AbelianGroupHomomorphism inclusionHomology(BigInteger degree) {
        requireDegree(degree); Computation work=new Computation();
        IntegralHomology first=IntegralHomology.atDegree(subcomplex,degree,work),second=IntegralHomology.atDegree(ambient,degree,work);
        return first.inducedMap(second,inclusionMatrix(degree,work),work);
    }
    public AbelianGroupHomomorphism quotientHomology(BigInteger degree) {
        requireDegree(degree); Computation work=new Computation();
        IntegralHomology first=IntegralHomology.atDegree(ambient,degree,work),second=homology(degree,work);
        return first.inducedMap(second,projectionMatrix(degree,work),work);
    }
    public AbelianGroupHomomorphism connectingHomology(BigInteger degree) {
        requireDegree(degree); Computation work=new Computation();
        return homology(degree,work).inducedMap(connectingTarget(degree,work),connectingChainMatrix(degree,work),work);
    }
    /** In order: H_k(A)->H_k(X), H_k(X)->H_k(X,A), H_k(X,A)->H_(k-1)(A). */
    public List<AbelianGroupHomomorphism> longExactSegment(BigInteger degree) {
        requireDegree(degree); Computation work=new Computation();
        IntegralHomology a=IntegralHomology.atDegree(subcomplex,degree,work),x=IntegralHomology.atDegree(ambient,degree,work),relative=homology(degree,work);
        AbelianGroupHomomorphism inclusion=a.inducedMap(x,inclusionMatrix(degree,work),work);
        AbelianGroupHomomorphism quotient=x.inducedMap(relative,projectionMatrix(degree,work),work);
        AbelianGroupHomomorphism connecting=relative.inducedMap(connectingTarget(degree,work),connectingChainMatrix(degree,work),work);
        return Collections.unmodifiableList(Arrays.asList(inclusion,quotient,connecting));
    }
    @Override public boolean equals(Object other) {
        if(!(other instanceof RelativeSimplicialComplex)) return false; RelativeSimplicialComplex pair=(RelativeSimplicialComplex)other;
        return ambient.equals(pair.ambient) && subcomplex.equals(pair.subcomplex);
    }
    @Override public int hashCode() { return Objects.hash(ambient,subcomplex); }
    @Override public String toString() { return "RelativeComplex(ambient="+ambient+", subcomplex="+subcomplex+")"; }
}
