package mathematics.core;

/** Representation, computation and evidence are intentionally independent axes. */
public final class MathStatus {
    private MathStatus() { }
    public enum Representation { DIRECTLY_SUPPORTED, SUPPORTED_WITH_COMPOSITION, REQUIRES_EXTENSION, NOT_FAITHFULLY_REPRESENTABLE }
    public enum Computation { EXACT, SYMBOLIC, NUMERICAL, APPROXIMATE, STOCHASTIC, INTERVAL_BOUND, UNKNOWN }
    public enum Epistemic { DEFINED, CONJECTURED, EMPIRICALLY_TESTED, COUNTEREXAMPLE_FOUND, MACHINE_CHECKED, HUMAN_REVIEWED, PROVED, FORMALLY_VERIFIED, REFUTED }
    public enum Membership { MEMBER, NOT_MEMBER, UNKNOWN }
    public enum Implementation { IMPLEMENTED, PARTIAL, CATALOG_ONLY, PROPOSED }
    public enum CollectionSemantics { SCALAR, LIST, SET, MULTISET, SEQUENCE, DISTRIBUTION, SOLUTION_FAMILY }
    public enum Solution { EXACT_SOLUTION, SYMBOLIC_SOLUTION, NUMERICAL_SOLUTION, APPROXIMATE_SOLUTION, PROVEN_EXISTENCE, PROVEN_UNIQUENESS, UNKNOWN }
    public enum Equality { LITERAL, MATHEMATICAL, ISOMORPHISM, HOMEOMORPHISM, DIFFEOMORPHISM, HOMOTOPY_EQUIVALENCE, CATEGORICAL_EQUIVALENCE, APPROXIMATE, NUMERICAL_TOLERANCE }
}
