"""Evidence claims must fail closed when registry entries drift."""
import copy
import json
import unittest
import coverage
import csv
import sync_native_catalog


class CoverageTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.data = json.loads(coverage.DATABASE.read_text(encoding="utf-8"))

    def changed(self, predicate, **updates):
        data = copy.deepcopy(self.data)
        next(x for x in data["concepts"] if predicate(x)).update(updates)
        return coverage.validate(data)

    def test_repository_registry_is_valid(self):
        self.assertEqual([], coverage.validate(self.data))

    def test_missing_extension_is_rejected(self):
        errors = self.changed(lambda r: r["representation_status"] == "REQUIRES_EXTENSION", required_extension=None)
        self.assertTrue(any("missing required extension" in x for x in errors))

    def test_missing_test_file_is_rejected(self):
        errors = self.changed(lambda r: r["machine_tested"], tests=["missing/DoesNotExistTest.java"])
        self.assertTrue(any("missing/unsafe path" in x for x in errors))

    def test_proof_claim_needs_evidence(self):
        errors = self.changed(lambda r: True, formal_verification_status="FORMALLY_VERIFIED", epistemic_status="PROVED")
        self.assertTrue(any("formal claim requires artifact" in x for x in errors))
        self.assertTrue(any("proof status without evidence" in x for x in errors))

    def test_human_review_needs_a_named_reviewer(self):
        errors = self.changed(lambda r: True, human_review_status="HUMAN_REVIEWED")
        self.assertTrue(any("unsupported human-review claim" in x for x in errors))

    def test_duplicate_identifier_is_rejected(self):
        data = copy.deepcopy(self.data)
        data["concepts"].append(data["concepts"][0])
        self.assertTrue(any("duplicate concept id" in x for x in coverage.validate(data)))

    def test_arity_cannot_disagree_with_operands(self):
        errors = self.changed(lambda r: r["record_kind"] == "OPERATION" and r["arity"] == 2, domain_B=None)
        self.assertTrue(any("arity/domain_B mismatch" in x for x in errors))

    def test_catalog_only_cannot_claim_tests(self):
        errors = self.changed(lambda r: r["implementation_status"] == "CATALOG_ONLY", machine_tested=True)
        self.assertTrue(any("catalog-only record cannot claim" in x for x in errors))

    def test_missing_requested_concept_is_rejected(self):
        data = copy.deepcopy(self.data)
        data["concepts"] = [r for r in data["concepts"] if r["id"] != "foundations.singleton"]
        self.assertTrue(any("missing specification concept" in x for x in coverage.validate(data)))

    def test_runtime_catalog_drift_is_rejected(self):
        errors = self.changed(lambda r: bool(r.get("runtime_operation_id")), runtime_operation_id="unknown-operation")
        self.assertTrue(any("runtime operation registry drift" in x for x in errors))

    def test_reports_are_deterministic(self):
        reversed_data = copy.deepcopy(self.data)
        reversed_data["concepts"].reverse()
        self.assertEqual(coverage.reports(self.data), coverage.reports(reversed_data))

    def test_native_interface_drift_is_rejected(self):
        errors = self.changed(lambda r: r.get("runtime_catalog") == "ConcreteMathematics",
                              legacy_operation_interface="ICustomMemberOperation")
        self.assertTrue(any("concrete runtime signature drift" in x for x in errors))

    def test_operation_conditions_are_scoped_to_the_algebra(self):
        records = {r.get("runtime_operation_id"): r for r in self.data["concepts"] if r.get("runtime_operation_id")}
        self.assertIn("negative group", " ".join(records["ConeChain.zero-on"]["required_invariants"]))
        self.assertIn("include(Fs)-lift(ds)", " ".join(records["ConeChain.lift-source"]["required_invariants"]))
        self.assertIn("positive degree", " ".join(records["ConeCochain.cobounding-cochain"]["required_invariants"]))
        self.assertIn("anticommutes", " ".join(records["ConeCochain.include-source"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["ConeChain.cycle-generators"]["known_limitations"]))
        self.assertIn("ILeftProjectionOperation", " ".join(records["ChainConeMap.on-chain"]["required_invariants"]))
        self.assertIn("second-carrier wrapper", " ".join(records["ChainConeMap.on-cochain"]["required_invariants"]))
        self.assertIn("bF->Ga", " ".join(records["ChainConeMap.from-data"]["required_invariants"]))
        self.assertIn("-H_(n-1)", " ".join(records["ChainConeMap.from-homotopy"]["required_invariants"]))
        self.assertIn("b_after H_before", " ".join(records["ChainConeMap.compose"]["required_invariants"]))
        self.assertIn("negative-degree source presentations", " ".join(records["ChainConeMap.homology-naturality-maps"]["required_invariants"]))
        self.assertIn("contravariant vertical maps", " ".join(records["ChainConeMap.cohomology-naturality-maps"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["ChainConeMap.homology-maps"]["known_limitations"]))
        self.assertIn("negative source boundary", " ".join(records["ChainCone.boundary-matrix"]["required_invariants"]))
        self.assertIn("ILeftProjectionOperation", " ".join(records["ChainCone.chain-rank"]["required_invariants"]))
        self.assertIn("negative-degree zero presentation", " ".join(records["ChainCone.projection-homology-map"]["required_invariants"]))
        self.assertIn("all four reductions", " ".join(records["ChainCone.long-exact-segment"]["required_invariants"]))
        self.assertIn("n+1", " ".join(records["ChainCone.long-exact-cohomology-segment"]["required_invariants"]))
        self.assertIn("combined cone degree rank", " ".join(records["ChainCone.homology"]["known_limitations"]))
        self.assertIn("5000000", " ".join(records["ChainMap.is-quasi-isomorphism"]["known_limitations"]))
        self.assertIn("does not invoke simultaneous inverse solving", " ".join(records["ChainMap.is-quasi-isomorphism"]["required_invariants"]))
        self.assertIn("negate the actual accumulated prism matrices", " ".join(records["ChainEquivalence.from-homotopy-equivalence"]["required_invariants"]))
        self.assertIn("square and unimodular", " ".join(records["ChainEquivalence.from-isomorphism"]["required_invariants"]))
        self.assertIn("zero target homotopy", " ".join(records["ChainEquivalence.from-collapse"]["required_invariants"]))
        self.assertIn("source witness is zero", " ".join(records["ChainEquivalence.from-subdivision"]["required_invariants"]))
        self.assertIn("dH(c)+H(dc)=c-GF(c)", " ".join(records["ChainEquivalence.source-homotopy-on-chain"]["required_invariants"]))
        self.assertIn("positive degree", " ".join(records["ChainEquivalence.target-homotopy-on-cochain"]["required_invariants"]))
        self.assertIn("complete conversion", " ".join(records["ChainEquivalence.from-collapse-sequence"]["known_limitations"]))
        self.assertIn("GJF+H, AKB+L", " ".join(records["ChainEquivalence.compose"]["required_invariants"]))
        self.assertIn("without inverse search", " ".join(records["ChainEquivalence.compose"]["required_invariants"]))
        self.assertIn("do not negate witnesses", " ".join(records["ChainEquivalence.inverse"]["required_invariants"]))
        self.assertIn("including degree zero", " ".join(records["ChainEquivalence.on-cochain"]["required_invariants"]))
        self.assertIn("ILeftProjectionOperation", " ".join(records["ChainEquivalence.on-chain"]["required_invariants"]))
        self.assertIn("shared two-map budget", " ".join(records["ChainEquivalence.homology-maps"]["required_invariants"]))
        self.assertIn("Homotopic but unequal", " ".join(records["ChainEquivalence.from-data"]["required_invariants"]))
        self.assertIn("256 total equations", " ".join(records["ChainEquivalence.from-map"]["known_limitations"]))
        self.assertIn("5000000", " ".join(records["ChainEquivalence.compose"]["known_limitations"]))
        self.assertIn("full labelled endpoint pairs", " ".join(records["ChainMapClass.equal"]["required_invariants"]))
        self.assertIn("right operand first", " ".join(records["ChainMapClass.compose"]["required_invariants"]))
        self.assertIn("set-theoretic section", " ".join(records["ChainMapClass.representative"]["required_invariants"]))
        self.assertIn("zero has order one", " ".join(records["ChainMapClass.order"]["required_invariants"]))
        self.assertIn("exact retained Hom presentation", " ".join(records["ChainMapClass.from-element"]["required_invariants"]))
        self.assertIn("ICustomMemberOperation", " ".join(records["ChainMapClass.scale"]["required_invariants"]))
        self.assertIn("torsion first", " ".join(records["ChainMapClass.generators-in"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["ChainMapClass.compose"]["known_limitations"]))
        self.assertIn("Both inverse identities", " ".join(records["ChainMap.is-homotopy-equivalence"]["required_invariants"]))
        self.assertIn("Free Smith coordinates", " ".join(records["ChainMap.homotopy-inverse"]["required_invariants"]))
        self.assertIn("[GF -> id_source, FG -> id_target]", " ".join(records["ChainHomotopy.inverse-homotopies"]["required_invariants"]))
        self.assertIn("homotopy category", " ".join(records["ChainMapClass.is-isomorphism"]["required_invariants"]))
        self.assertIn("shared solve-and-normalization budget", " ".join(records["ChainMapClass.inverse"]["required_invariants"]))
        self.assertIn("256 total equations", " ".join(records["ChainMap.is-homotopy-equivalence"]["known_limitations"]))
        self.assertIn("256 total unknown coefficients", " ".join(records["ChainHomotopy.inverse-homotopies"]["known_limitations"]))
        self.assertIn("separately successful stages", " ".join(records["ChainMapClass.inverse"]["known_limitations"]))
        self.assertIn("including degree zero and the top degree", " ".join(records["ChainHomotopy.from-data"]["required_invariants"]))
        self.assertIn("negate the actual witness matrices", " ".join(records["ChainHomotopy.reverse"]["required_invariants"]))
        self.assertIn("exact full joining chain map", " ".join(records["ChainHomotopy.then"]["required_invariants"]))
        self.assertIn("A_(k+1) H_k", " ".join(records["ChainHomotopy.postcompose"]["required_invariants"]))
        self.assertIn("Q^0 has zero rows", " ".join(records["ChainHomotopy.cochain-matrix"]["required_invariants"]))
        self.assertIn("positive degree", " ".join(records["ChainHomotopy.on-cochain"]["required_invariants"]))
        self.assertIn("ILeftProjectionOperation", " ".join(records["ChainHomotopy.on-chain"]["required_invariants"]))
        self.assertIn("exactly [from_*,to_*]", " ".join(records["ChainHomotopy.homology-maps"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["ChainHomotopy.from-subdivision"]["known_limitations"]))
        self.assertIn("No geometric homotopy search", " ".join(records["ChainHomotopy.stationary"]["known_limitations"]))
        self.assertIn("homology maps alone is insufficient", " ".join(records["ChainHomotopy.are-homotopic"]["required_invariants"]))
        self.assertIn("free Smith coordinates zero", " ".join(records["ChainHomotopy.between"]["required_invariants"]))
        self.assertIn("zero-to-zero homogeneous witnesses", " ".join(records["ChainHomotopy.solution-generators"]["required_invariants"]))
        self.assertIn("257 entries", " ".join(records["ChainHomotopy.solution-generators"]["required_invariants"]))
        self.assertIn("256 total equations", " ".join(records["ChainHomotopy.are-homotopic"]["known_limitations"]))
        self.assertIn("256 total unknown coefficients", " ".join(records["ChainHomotopy.solution-generators"]["known_limitations"]))
        self.assertIn("delta_0(F) = d_target F - F d_source", " ".join(records["ChainMapSpace.homology"]["required_invariants"]))
        self.assertIn("torsion invisible", " ".join(records["ChainMapSpace.homotopy-group"]["required_invariants"]))
        self.assertIn("free cycle lattice before quotienting", " ".join(records["ChainMapSpace.map-generators"]["required_invariants"]))
        self.assertIn("set-theoretic section", " ".join(records["ChainMapSpace.representative"]["required_invariants"]))
        self.assertIn("torsion generators first", " ".join(records["ChainMapSpace.representatives"]["required_invariants"]))
        self.assertIn("256 total Hom coefficients", " ".join(records["ChainMapSpace.class-of"]["known_limitations"]))
        self.assertIn("contravariant", " ".join(records["ChainMapSpace.precompose-map"]["required_invariants"]))
        self.assertIn("covariant", " ".join(records["ChainMapSpace.postcompose-map"]["required_invariants"]))
        self.assertIn("ICustomMemberOperation", " ".join(records["ChainMapSpace.precompose-space"]["required_invariants"]))
        self.assertIn("degrees [-1,0,1]", " ".join(records["ChainMapSpace.precompose-matrices"]["required_invariants"]))
        self.assertIn("A_(k+j) T_k", " ".join(records["ChainMapSpace.postcompose-matrices"]["required_invariants"]))
        self.assertIn("both complete Hom reductions", " ".join(records["ChainMapSpace.postcompose-map"]["known_limitations"]))
        self.assertIn("including the top degree", " ".join(records["ChainMap.from-data"]["required_invariants"]))
        self.assertIn("right operand first", " ".join(records["ChainMap.compose"]["required_invariants"]))
        self.assertIn("unimodular over Z", " ".join(records["ChainMap.inverse"]["required_invariants"]))
        self.assertIn("ILeftProjectionOperation", " ".join(records["ChainMap.on-chain"]["required_invariants"]))
        self.assertIn("Both endpoint subcomplexes", " ".join(records["ChainMap.on-absolute-cochain"]["required_invariants"]))
        self.assertIn("composition reverses order", " ".join(records["ChainMap.cohomology-map"]["required_invariants"]))
        self.assertIn("entire list", " ".join(records["ChainMap.homology-maps"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["ChainMap.from-collapse-sequence"]["known_limitations"]))
        self.assertIn("need not preserve augmentation or cup products", " ".join(records["ChainMap.on-cochain"]["known_limitations"]))
        polynomial = " ".join(records["Q[x].quotient"]["required_invariants"])
        self.assertIn("Euclidean", polynomial)
        self.assertNotIn("truncates", polynomial)
        self.assertIn("truncates", " ".join(records["Z.quotient"]["required_invariants"]))
        self.assertIn("f(g(x))", " ".join(records["Q(x).compose"]["required_invariants"]))
        self.assertIn("first relation", " ".join(records["FiniteRelation(Z,Z).compose"]["required_invariants"]))
        self.assertIn("Every permutation", " ".join(records["S3.inverse"]["required_invariants"]))
        self.assertNotIn("10000", " ".join(records["S3.orbit"]["known_limitations"]))
        self.assertIn("10000", " ".join(records["Q[x].orbit"]["known_limitations"]))
        self.assertIn("must be a unit", " ".join(records["Z/6Z.inverse"]["required_invariants"]))
        self.assertIn("nonzero alone is insufficient", " ".join(records["Z/6Z.divide"]["required_invariants"]))
        self.assertIn("empty list", " ".join(records["Z/6Z.solve-multiply"]["required_invariants"]))
        self.assertIn("bijection", " ".join(records["FiniteFunction(Z,Z).inverse"]["required_invariants"]))
        self.assertIn("f(g(x))", " ".join(records["FiniteFunction(Z,Z).compose"]["required_invariants"]))
        self.assertIn("path order", " ".join(records["FiniteCategory.compose"]["required_invariants"]))
        self.assertIn("arrow label", " ".join(records["FiniteCategory.source"]["required_invariants"]))
        self.assertIn("Strict inverse", " ".join(records["FiniteFunctor.inverse"]["required_invariants"]))
        self.assertIn("each source hom set", " ".join(records["FiniteFunctor.is-faithful"]["required_invariants"]))
        self.assertIn("Every component", " ".join(records["FiniteNaturalTransformation.inverse"]["required_invariants"]))
        self.assertIn("Vertical composition", " ".join(records["FiniteNaturalTransformation.compose"]["required_invariants"]))
        self.assertIn("Every validated equivalence", " ".join(records["FiniteEquivalence.inverse"]["required_invariants"]))
        self.assertIn("full, faithful and essentially surjective", " ".join(records["FiniteEquivalence.from-functor"]["required_invariants"]))
        self.assertIn("right adjoint must exist", " ".join(records["FiniteAdjunction.from-left"]["required_invariants"]))
        self.assertIn("Swap adjoint roles", " ".join(records["FiniteAdjunction.opposite"]["required_invariants"]))
        self.assertIn("must be invertible", " ".join(records["FiniteAdjunction.to-equivalence"]["required_invariants"]))
        self.assertIn("entire diagram", " ".join(records["FiniteCone.lift"]["required_invariants"]))
        self.assertIn("never false", " ".join(records["FiniteCone.is-limit"]["required_invariants"]))
        self.assertIn("1000000", " ".join(records["FiniteCone.limit"]["known_limitations"]))
        self.assertIn("first vertex to the second", " ".join(records["FiniteCocone.descend"]["required_invariants"]))
        self.assertIn("end at the constant", " ".join(records["FiniteCocone.from-transformation"]["required_invariants"]))
        self.assertIn("never false", " ".join(records["FiniteCocone.is-colimit"]["required_invariants"]))
        self.assertIn("same dimension", " ".join(records["Vec(Q).dot"]["required_invariants"]))
        self.assertIn("square and nonsingular", " ".join(records["Mat(Q).inverse"]["required_invariants"]))
        self.assertIn("Inconsistent systems return an empty", " ".join(records["Affine(Q).solve"]["required_invariants"]))
        self.assertNotIn("must be nonsingular", " ".join(records["Affine(Q).solve"]["required_invariants"]))
        self.assertIn("including zero matrices", " ".join(records["Mat(Q).pseudoinverse"]["required_invariants"]))
        self.assertIn("nonempty affine", " ".join(records["Affine(Q).least-squares"]["required_invariants"]))
        self.assertIn("need not equal", " ".join(records["Affine(Q).minimum-norm"]["required_invariants"]))
        self.assertIn("distinct, present and equal-sized", " ".join(records["Tensor(Q).contract"]["required_invariants"]))
        self.assertIn("not tensor decomposition rank", " ".join(records["Tensor(Q).order"]["required_invariants"]))
        self.assertIn("both dimensions positive", " ".join(records["Tensor(Q).to-matrix"]["required_invariants"]))
        self.assertIn("Repeated basis factors vanish", " ".join(records["Exterior(Q).wedge"]["required_invariants"]))
        self.assertIn("oriented orthonormal", " ".join(records["Exterior(Q).hodge-star"]["required_invariants"]))
        self.assertIn("covariant induced map", " ".join(records["Exterior(Q).apply"]["required_invariants"]))
        self.assertIn("x*b=a", " ".join(records["H(Q).divide-right"]["required_invariants"]))
        self.assertIn("b*x=a", " ".join(records["H(Q).divide-left"]["required_invariants"]))
        self.assertIn("no approximation", " ".join(records["H(Q).from-rotation-matrix"]["required_invariants"]))
        self.assertIn("variable-independent polynomial", " ".join(records["Poly(Q).primitive"]["required_invariants"]))
        self.assertIn("not normalized", " ".join(records["Poly(Q).directional"]["required_invariants"]))
        self.assertIn("degree -1", " ".join(records["Poly(Q).degree"]["required_invariants"]))
        self.assertIn("right operand first", " ".join(records["PolynomialMap(Q).compose"]["required_invariants"]))
        self.assertNotIn("first relation", " ".join(records["PolynomialMap(Q).compose"]["required_invariants"]))
        self.assertIn("rows index output", " ".join(records["PolynomialMap(Q).jacobian-at"]["required_invariants"]))
        self.assertIn("right-handed", " ".join(records["PolynomialMap(Q).curl"]["required_invariants"]))
        self.assertIn("contravariant", " ".join(records["PolynomialForm(Q).pullback"]["required_invariants"]))
        self.assertIn("d squared is zero", " ".join(records["PolynomialForm(Q).exterior-derivative"]["required_invariants"]))
        self.assertIn("Cartan", " ".join(records["PolynomialForm(Q).lie-derivative"]["required_invariants"]))
        self.assertIn("Every coefficient is a constant", " ".join(records["PolynomialForm(Q).to-exterior"]["required_invariants"]))
        self.assertIn("top-degree", " ".join(records["PolynomialForm(Q).integrate-unit-cube"]["required_invariants"]))
        self.assertIn("no absolute Jacobian", " ".join(records["PolynomialCell(Q).integrate"]["required_invariants"]))
        self.assertIn("even for a zero chain", " ".join(records["PolynomialChain(Q).integrate"]["required_invariants"]))
        self.assertIn("degree -1", " ".join(records["PolynomialChain(Q).boundary"]["required_invariants"]))
        self.assertIn("shared work budget", " ".join(records["PolynomialChain(Q).pushforward"]["required_invariants"]))
        self.assertIn("det(x*I-A)", " ".join(records["Mat(Q).characteristic-polynomial"]["required_invariants"]))
        self.assertIn("least degree", " ".join(records["Mat2(Q).minimal-polynomial"]["required_invariants"]))
        self.assertIn("second matrix carrier", " ".join(records["Mat(Q).evaluate-at-matrix"]["required_invariants"]))
        self.assertIn("never false", " ".join(records["Mat(Q).is-diagonalizable-over-q"]["required_invariants"]))
        self.assertIn("A*P=P*D", " ".join(records["Mat2(Q).diagonalize-over-q"]["required_invariants"]))
        self.assertIn("not a Jordan chain", " ".join(records["Mat(Q).generalized-eigenspace-basis"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["Mat(Q).minimal-polynomial"]["known_limitations"]))
        self.assertIn("never a partial list", " ".join(records["Q[x].rational-roots"]["required_invariants"]))
        self.assertIn("zero polynomial", " ".join(records["Q[x].root-multiplicity"]["required_invariants"]))
        self.assertIn("second kernel first", " ".join(records["FiniteMarkov(Z).compose"]["required_invariants"]))
        self.assertIn("second operand's", " ".join(records["FiniteMarkov(Z).apply"]["required_invariants"]))
        self.assertIn("not random sample paths", " ".join(records["FiniteMarkov(Z).orbit"]["required_invariants"]))
        self.assertIn("not enumerate all stationary laws", " ".join(records["FiniteMarkov(Z).stationary-extremes"]["required_invariants"]))
        self.assertIn("strictly positive", " ".join(records["FiniteMarkov(Z).reverse"]["required_invariants"]))
        self.assertIn("infinite expectation", " ".join(records["FiniteMarkov(Z).mean-hitting-times"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["FiniteMarkov(Z).power"]["known_limitations"]))
        self.assertIn("source first", " ".join(records["AbelianGroupType.hom-group"]["required_invariants"]))
        self.assertIn("source first", " ".join(records["AbelianGroupType.ext1"]["required_invariants"]))
        self.assertIn("n=0 denoting Z", " ".join(records["AbelianGroupType.cyclic"]["required_invariants"]))
        self.assertIn("free rank must be zero", " ".join(records["AbelianGroupType.order"]["required_invariants"]))
        self.assertIn("unreduced", " ".join(records["FiniteComplex.integral-homology"]["required_invariants"]))
        self.assertIn("existing F2", " ".join(records["FiniteComplex.rational-betti-number"]["required_invariants"]))
        self.assertIn("including unit factors", " ".join(records["FiniteComplex.boundary-invariant-factors"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["FiniteComplex.integral-homology-groups"]["known_limitations"]))
        self.assertIn("denominator one", " ".join(records["Vec(Z).from-rational"]["required_invariants"]))
        self.assertIn("[U,D,V]", " ".join(records["Mat(Z).smith-decomposition"]["required_invariants"]))
        self.assertIn("whole integer kernel", " ".join(records["Mat(Z).kernel-basis"]["required_invariants"]))
        self.assertIn("not the saturation", " ".join(records["Mat(Z).image-basis"]["required_invariants"]))
        self.assertIn("particular solution first", " ".join(records["Mat(Z).solve-generators"]["required_invariants"]))
        self.assertIn("never false", " ".join(records["Mat(Z).has-integer-solution"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["Mat(Z).inverse-unimodular"]["known_limitations"]))
        self.assertIn("0 by vertex-count", " ".join(records["FiniteComplex.boundary-matrix"]["required_invariants"]))
        self.assertIn("columns", " ".join(records["PresentedAbelianGroup.from-matrix"]["required_invariants"]))
        self.assertIn("not merely", " ".join(records["PresentedAbelianGroup.equal"]["required_invariants"]))
        self.assertIn("ambient group is infinite", " ".join(records["AbelianGroupElement.order"]["required_invariants"]))
        self.assertIn("Infinite fibers are undefined", " ".join(records["AbelianGroupElement.multiplication-preimages"]["required_invariants"]))
        self.assertIn("first-carrier wrappers", " ".join(records["AbelianGroupElement.multiplication-preimages"]["required_invariants"]))
        self.assertIn("second Vec(Z)", " ".join(records["AbelianGroupElement.reduce"]["required_invariants"]))
        self.assertIn("4096", " ".join(records["AbelianGroupElement.elements"]["known_limitations"]))
        self.assertIn("right operand first", " ".join(records["AbelianGroupHomomorphism.compose"]["required_invariants"]))
        self.assertIn("K*C=R_source", " ".join(records["AbelianGroupHomomorphism.kernel"]["required_invariants"]))
        self.assertIn("second AbelianGroupElement", " ".join(records["AbelianGroupHomomorphism.apply"]["required_invariants"]))
        self.assertIn("coset by the kernel", " ".join(records["AbelianGroupHomomorphism.preimage"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["AbelianGroupHomomorphism.inverse"]["known_limitations"]))
        self.assertIn("compose to zero", " ".join(records["IntegralHomology.from-boundaries"]["required_invariants"]))
        self.assertIn("second Vec(Z)", " ".join(records["IntegralHomology.bounding-chain"]["required_invariants"]))
        self.assertIn("need not be additive", " ".join(records["IntegralHomology.representative"]["required_invariants"]))
        self.assertIn("preserve cycles and boundaries", " ".join(records["IntegralHomology.induced-map"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["IntegralHomology.generators"]["known_limitations"]))
        self.assertIn("collapsed simplices map to zero", " ".join(records["SimplicialMap.chain-matrix"]["required_invariants"]))
        self.assertIn("Vertex bijectivity alone is insufficient", " ".join(records["SimplicialMap.inverse"]["required_invariants"]))
        self.assertIn("entire list", " ".join(records["SimplicialMap.homology-maps"]["required_invariants"]))
        self.assertIn("second Z wrappers", " ".join(records["SimplicialMap.vertex-fiber"]["required_invariants"]))
        self.assertIn("4096", " ".join(records["SimplicialMap.compose"]["known_limitations"]))
        self.assertIn("labelled subcomplex", " ".join(records["RelativeComplex.from-complexes"]["required_invariants"]))
        self.assertIn("generally not a chain map", " ".join(records["RelativeComplex.lift-matrix"]["required_invariants"]))
        self.assertIn("H_-1(A)=0", " ".join(records["RelativeComplex.connecting-homology"]["required_invariants"]))
        self.assertIn("entire three-map segment", " ".join(records["RelativeComplex.long-exact-segment"]["required_invariants"]))
        self.assertIn("entire list", " ".join(records["RelativeComplex.homology-degrees"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["RelativeComplex.homology"]["known_limitations"]))
        self.assertIn("f(A) contained in B", " ".join(records["RelativeMap.from-map"]["required_invariants"]))
        self.assertIn("images in B give zero columns", " ".join(records["RelativeMap.chain-matrix"]["required_invariants"]))
        self.assertIn("Ambient contiguity alone is insufficient", " ".join(records["RelativeMap.contiguous"]["required_invariants"]))
        self.assertIn("all four maps", " ".join(records["RelativeMap.long-exact-maps"]["required_invariants"]))
        self.assertIn("entire list", " ".join(records["RelativeMap.homology-maps"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["RelativeMap.long-exact-maps"]["known_limitations"]))
        self.assertIn("(i,-j)", " ".join(records["SimplicialCover.intersection-matrix"]["required_invariants"]))
        self.assertIn("generally not a chain map", " ".join(records["SimplicialCover.split-matrix"]["required_invariants"]))
        self.assertIn("H_-1(I)=0", " ".join(records["SimplicialCover.connecting-homology-map"]["required_invariants"]))
        self.assertIn("entire three-map segment", " ".join(records["SimplicialCover.long-exact-segment"]["required_invariants"]))
        self.assertIn("need not be invertible", " ".join(records["SimplicialCover.excision-map"]["required_invariants"]))
        self.assertIn("sum of both chain ranks", " ".join(records["SimplicialCover.sum-homology"]["known_limitations"]))
        self.assertIn("every simplex of A", " ".join(records["CoverMap.from-map"]["required_invariants"]))
        self.assertIn("complete ordered middle covers", " ".join(records["CoverMap.compose"]["required_invariants"]))
        self.assertIn("all four maps", " ".join(records["CoverMap.long-exact-maps"]["required_invariants"]))
        self.assertIn("Ambient contiguity alone is insufficient", " ".join(records["CoverMap.contiguous"]["required_invariants"]))
        self.assertIn("strictly contain f(I)", " ".join(records["CoverMap.image"]["required_invariants"]))
        self.assertIn("as RelativeMap values", " ".join(records["CoverMap.excision-maps"]["required_invariants"]))
        self.assertIn("entire list", " ".join(records["CoverMap.sum-homology-maps"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["CoverMap.long-exact-maps"]["known_limitations"]))
        self.assertIn("need not commute", " ".join(records["CoverMap.long-exact-maps"]["known_limitations"]))
        self.assertIn("left minus right", " ".join(records["SimplicialCover.difference-matrix"]["required_invariants"]))
        self.assertIn("H^(k+1)(U)", " ".join(records["SimplicialCover.connecting-cohomology-map"]["required_invariants"]))
        self.assertIn("entire three-map segment", " ".join(records["SimplicialCover.long-exact-cohomology-segment"]["required_invariants"]))
        self.assertIn("including torsion", " ".join(records["SimplicialCover.sum-cohomology"]["required_invariants"]))
        self.assertIn("composition reverses order", " ".join(records["CoverMap.sum-cohomology-map"]["required_invariants"]))
        self.assertIn("four target-to-source", " ".join(records["CoverMap.long-exact-cohomology-maps"]["required_invariants"]))
        self.assertIn("entire list", " ".join(records["CoverMap.sum-cohomology-maps"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["CoverMap.long-exact-cohomology-maps"]["known_limitations"]))
        self.assertIn("zero group in degree -1", " ".join(records["SimplicialChain.boundary"]["required_invariants"]))
        self.assertIn("first carrier", " ".join(records["SimplicialChain.cap"]["required_invariants"]))
        self.assertIn("equal degrees", " ".join(records["SimplicialChain.evaluate"]["required_invariants"]))
        self.assertIn("cycle and a cocycle", " ".join(records["SimplicialChain.cap-class"]["required_invariants"]))
        self.assertIn("H_n->H_(n-p)", " ".join(records["SimplicialChain.cap-homology-map"]["required_invariants"]))
        self.assertIn("map need not be an isomorphism", " ".join(records["SimplicialChain.cap-cohomology-map"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["SimplicialChain.cap-cohomology-map"]["known_limitations"]))
        self.assertIn("not generally natural on chains", " ".join(records["SimplicialChain.cap"]["known_limitations"]))
        self.assertIn("input need not vanish on A", " ".join(records["RelativeChain.from-absolute"]["required_invariants"]))
        self.assertIn("generally not a chain map", " ".join(records["RelativeChain.lift-absolute"]["required_invariants"]))
        self.assertIn("full subcomplex A", " ".join(records["RelativeChain.connect-cycle"]["required_invariants"]))
        self.assertIn("same pair", " ".join(records["RelativeChain.cap"]["required_invariants"]))
        self.assertIn("back faces in A must be retained", " ".join(records["RelativeChain.relative-cap"]["required_invariants"]))
        self.assertIn("H^p(X,A)->H_(n-p)(X)", " ".join(records["RelativeChain.relative-cap-cohomology-map"]["required_invariants"]))
        self.assertIn("ignore its coordinates", " ".join(records["RelativeChain.relative-cap-matrix"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["RelativeChain.relative-cap-homology-map"]["known_limitations"]))
        self.assertIn("B contained in D", " ".join(records["RelativeCap.on"]["required_invariants"]))
        self.assertIn("D exactly equal to A union B", " ".join(records["RelativeCap.cap"]["required_invariants"]))
        self.assertIn("outside B", " ".join(records["RelativeCap.cap"]["required_invariants"]))
        self.assertIn("ignore the stored chain coordinates", " ".join(records["RelativeCap.cap-matrix"]["required_invariants"]))
        self.assertIn("need not be a cocycle", " ".join(records["RelativeCap.cap-cohomology-map"]["required_invariants"]))
        self.assertIn("H^p(X,A)->H_(n-p)(X,B)", " ".join(records["RelativeCap.cap-cohomology-map"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["RelativeCap.cap-homology-map"]["known_limitations"]))
        self.assertIn("B contained in A", " ".join(records["RelativeTriple.from-pair"]["required_invariants"]))
        self.assertIn("generally not a chain map", " ".join(records["RelativeTriple.lift-matrix"]["required_invariants"]))
        self.assertIn("H_k(X,A)->H_(k-1)(A,B)", " ".join(records["RelativeTriple.connecting-homology"]["required_invariants"]))
        self.assertIn("H^k(A,B)->H^(k+1)(X,A)", " ".join(records["RelativeTriple.connecting-cohomology"]["required_invariants"]))
        self.assertIn("ILeftProjectionOperation", " ".join(records["RelativeTriple.connect-cycle"]["required_invariants"]))
        self.assertIn("full inner pair", " ".join(records["RelativeTriple.connect-cocycle"]["required_invariants"]))
        self.assertIn("entire list", " ".join(records["RelativeTriple.long-exact-segment"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["RelativeTriple.long-exact-cohomology-segment"]["known_limitations"]))
        self.assertIn("B maps into D", " ".join(records["TripleMap.from-map"]["required_invariants"]))
        self.assertIn("all three", " ".join(records["TripleMap.inclusion"]["required_invariants"]))
        self.assertIn("middle and base", " ".join(records["TripleMap.contiguous"]["required_invariants"]))
        self.assertIn("four source-to-target", " ".join(records["TripleMap.long-exact-maps"]["required_invariants"]))
        self.assertIn("degree-minus-one presentations", " ".join(records["TripleMap.long-exact-maps"]["required_invariants"]))
        self.assertIn("four target-to-source", " ".join(records["TripleMap.long-exact-cohomology-maps"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["TripleMap.long-exact-cohomology-maps"]["known_limitations"]))
        self.assertIn("both the ambient target and its subcomplex", " ".join(records["SimplicialHomotopy.between"]["required_invariants"]))
        self.assertIn("to# - from#", " ".join(records["SimplicialHomotopy.chain-matrix"]["required_invariants"]))
        self.assertIn("zero rows", " ".join(records["SimplicialHomotopy.cochain-matrix"]["required_invariants"]))
        self.assertIn("ILeftProjectionOperation", " ".join(records["SimplicialHomotopy.on-chain"]["required_invariants"]))
        self.assertIn("positive degree", " ".join(records["SimplicialHomotopy.on-cochain"]["required_invariants"]))
        self.assertIn("empty subcomplexes", " ".join(records["SimplicialHomotopy.on-absolute-chain"]["required_invariants"]))
        self.assertIn("entire list", " ".join(records["SimplicialHomotopy.chain-matrices"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["SimplicialHomotopy.cochain-matrices"]["known_limitations"]))
        self.assertIn("zero-step path", " ".join(records["HomotopyPath.stationary-on"]["required_invariants"]))
        self.assertIn("equal full joining maps", " ".join(records["HomotopyPath.then"]["required_invariants"]))
        self.assertIn("including repeated stages", " ".join(records["HomotopyPath.stages"]["required_invariants"]))
        self.assertIn("to# - from#", " ".join(records["HomotopyPath.chain-matrix"]["required_invariants"]))
        self.assertIn("every degree and every step", " ".join(records["HomotopyPath.chain-matrices"]["required_invariants"]))
        self.assertIn("ILeftProjectionOperation", " ".join(records["HomotopyPath.on-chain"]["required_invariants"]))
        self.assertIn("need not equal", " ".join(records["HomotopyPath.precompose"]["required_invariants"]))
        self.assertIn("composition/validation budget", " ".join(records["HomotopyPath.postcompose"]["required_invariants"]))
        self.assertIn("256 stages", " ".join(records["HomotopyPath.append"]["known_limitations"]))
        self.assertIn("Id_X -> g after f and Id_Y -> f after g", " ".join(records["HomotopyEquivalence.from-maps"]["required_invariants"]))
        self.assertIn("does not yet require opposite boundaries", " ".join(records["HomotopyEquivalence.maps"]["required_invariants"]))
        self.assertIn("both transported/concatenated paths", " ".join(records["HomotopyEquivalence.compose"]["required_invariants"]))
        self.assertIn("Do not reverse either path", " ".join(records["HomotopyEquivalence.inverse"]["required_invariants"]))
        self.assertIn("both complete witness stage lists", " ".join(records["HomotopyEquivalence.equal"]["required_invariants"]))
        self.assertIn("exactly [f_*,g_*]", " ".join(records["HomotopyEquivalence.homology-maps"]["required_invariants"]))
        self.assertIn("exactly [f^*,g^*]", " ".join(records["HomotopyEquivalence.cohomology-maps"]["required_invariants"]))
        self.assertIn("H^n(Y,B)->H^n(X,A)", " ".join(records["HomotopyEquivalence.forward-cohomology-map"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["HomotopyEquivalence.compose"]["known_limitations"]))
        self.assertIn("ILeftProjectionFlatOperation", " ".join(records["HomotopyEquivalence.dominators"]["required_invariants"]))
        self.assertIn("subcomplex", " ".join(records["HomotopyEquivalence.dominators"]["required_invariants"]))
        self.assertIn("pair-relative minimality", " ".join(records["HomotopyEquivalence.is-strong-core"]["required_invariants"]))
        self.assertIn("one-step source path", " ".join(records["HomotopyEquivalence.collapse-vertex"]["required_invariants"]))
        self.assertIn("least compatible dominator", " ".join(records["HomotopyEquivalence.strong-core"]["required_invariants"]))
        self.assertIn("no partial core", " ".join(records["HomotopyEquivalence.strong-core"]["required_invariants"]))
        self.assertIn("255 deletions", " ".join(records["HomotopyEquivalence.strong-core-absolute"]["known_limitations"]))
        self.assertIn("not ordinary homotopy type", " ".join(records["HomotopyEquivalence.strongly-equivalent"]["required_invariants"]))
        self.assertIn("both reductions, search, maps and final validation", " ".join(records["HomotopyEquivalence.strong-equivalence-to"]["required_invariants"]))
        self.assertIn("64 vertices", " ".join(records["HomotopyEquivalence.strongly-equivalent"]["known_limitations"]))
        self.assertIn("same ambient dictionary", " ".join(records["SimplicialSubdivision.from-pair"]["required_invariants"]))
        self.assertIn("size first, then lexicographic", " ".join(records["SimplicialSubdivision.vertex-faces"]["required_invariants"]))
        self.assertIn("nonempty original ambient simplex", " ".join(records["SimplicialSubdivision.face-vertex"]["required_invariants"]))
        self.assertIn("ILeftProjectionOperation", " ".join(records["SimplicialSubdivision.map"]["required_invariants"]))
        self.assertIn("including collapsed faces", " ".join(records["SimplicialSubdivision.map"]["required_invariants"]))
        self.assertIn("from l_Y after sd(f) to f after l_X", " ".join(records["SimplicialSubdivision.naturality-homotopy"]["required_invariants"]))
        self.assertIn("H_n(sd X,sd A)->H_n(X,A)", " ".join(records["SimplicialSubdivision.homology-map"]["required_invariants"]))
        self.assertIn("H^n(X,A)->H^n(sd X,sd A)", " ".join(records["SimplicialSubdivision.cohomology-map"]["required_invariants"]))
        self.assertIn("exactly [l_*, inverse(l_*)]", " ".join(records["SimplicialSubdivision.homology-maps"]["required_invariants"]))
        self.assertIn("exactly [l^*, inverse(l^*)]", " ".join(records["SimplicialSubdivision.cohomology-maps"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["SimplicialSubdivision.inverse-homology-map"]["known_limitations"]))
        self.assertIn("need not preserve strong homotopy type", " ".join(records["SimplicialSubdivision.from-complex"]["known_limitations"]))
        self.assertIn("C_n(X,A)->C_n(sd X,sd A)", " ".join(records["SimplicialSubdivision.chain-matrix"]["required_invariants"]))
        self.assertIn("l# S = identity", " ".join(records["SimplicialSubdivision.chain-matrix"]["required_invariants"]))
        self.assertIn("C^n(sd X,sd A)->C^n(X,A)", " ".join(records["SimplicialSubdivision.cochain-matrix"]["required_invariants"]))
        self.assertIn("ILeftProjectionOperation", " ".join(records["SimplicialSubdivision.on-chain"]["required_invariants"]))
        self.assertIn("full subdivided pair", " ".join(records["SimplicialSubdivision.on-cochain"]["required_invariants"]))
        self.assertIn("identity - S l#", " ".join(records["SimplicialSubdivision.chain-homotopy-matrix"]["required_invariants"]))
        self.assertIn("final quotient projection", " ".join(records["SimplicialSubdivision.chain-homotopy-matrix"]["required_invariants"]))
        self.assertIn("zero rows", " ".join(records["SimplicialSubdivision.cochain-homotopy-matrix"]["required_invariants"]))
        self.assertIn("positive degree", " ".join(records["SimplicialSubdivision.homotopy-on-cochain"]["required_invariants"]))
        self.assertIn("empty original subcomplex", " ".join(records["SimplicialSubdivision.homotopy-on-absolute-chain"]["required_invariants"]))
        self.assertIn("entire immutable list", " ".join(records["SimplicialSubdivision.chain-matrices"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["SimplicialSubdivision.cochain-homotopy-matrices"]["known_limitations"]))
        self.assertIn("smallest size", " ".join(records["CollapseSequence.reduce"]["required_invariants"]))
        self.assertIn("no partial sequence", " ".join(records["CollapseSequence.reduce"]["required_invariants"]))
        self.assertIn("ICustomMemberOperation", " ".join(records["CollapseSequence.append"]["required_invariants"]))
        self.assertIn("full labelled joining pairs", " ".join(records["CollapseSequence.then"]["required_invariants"]))
        self.assertIn("one source stage", " ".join(records["CollapseSequence.stages"]["required_invariants"]))
        self.assertIn("Equal endpoints alone", " ".join(records["CollapseSequence.equal"]["required_invariants"]))
        self.assertIn("R i# = identity", " ".join(records["CollapseSequence.chain-matrix"]["required_invariants"]))
        self.assertIn("H_1 + i_1 H_2 R_1", " ".join(records["CollapseSequence.chain-homotopy-matrix"]["required_invariants"]))
        self.assertIn("ILeftProjectionOperation", " ".join(records["CollapseSequence.on-chain"]["required_invariants"]))
        self.assertIn("positive degree", " ".join(records["CollapseSequence.homotopy-on-cochain"]["required_invariants"]))
        self.assertIn("exactly [R_*,i_*]", " ".join(records["CollapseSequence.homology-maps"]["required_invariants"]))
        self.assertIn("exactly [R^*,i^*]", " ".join(records["CollapseSequence.cohomology-maps"]["required_invariants"]))
        self.assertIn("256 steps", " ".join(records["CollapseSequence.reduce"]["known_limitations"]))
        self.assertIn("5000000", " ".join(records["CollapseSequence.then"]["known_limitations"]))
        self.assertIn("including intermediate bases", " ".join(records["CollapseSequence.chain-matrices"]["known_limitations"]))
        self.assertIn("need not find a point", " ".join(records["CollapseSequence.reduce-absolute"]["known_limitations"]))
        self.assertIn("exact labelled target pair", " ".join(records["CollapseSequence.can-collapse-to"]["required_invariants"]))
        self.assertIn("original subcomplex intersected", " ".join(records["CollapseSequence.can-collapse-to"]["required_invariants"]))
        self.assertIn("depth-first order", " ".join(records["CollapseSequence.collapse-to"]["required_invariants"]))
        self.assertIn("successful suffixes are revisited", " ".join(records["CollapseSequence.collapses-to"]["required_invariants"]))
        self.assertIn("never truncated", " ".join(records["CollapseSequence.collapses-to"]["required_invariants"]))
        self.assertIn("1024 results", " ".join(records["CollapseSequence.absolute-collapses-to"]["required_invariants"]))
        self.assertIn("not contractibility or trivial homology", " ".join(records["CollapseSequence.is-collapsible"]["required_invariants"]))
        self.assertIn("empty complex false", " ".join(records["CollapseSequence.is-collapsible"]["required_invariants"]))
        self.assertIn("vertex is not prescribed", " ".join(records["CollapseSequence.collapse-to-point"]["required_invariants"]))
        self.assertIn("different surviving vertices", " ".join(records["CollapseSequence.collapses-to-point"]["required_invariants"]))
        self.assertIn("4096 distinct intermediate pairs", " ".join(records["CollapseSequence.can-collapse-to"]["known_limitations"]))
        self.assertIn("validation of every returned witness", " ".join(records["CollapseSequence.collapses-to-point"]["known_limitations"]))
        self.assertIn("both inside or both outside", " ".join(records["SimplicialCollapse.from-face"]["required_invariants"]))
        self.assertIn("only strict coface", " ".join(records["SimplicialCollapse.from-face"]["required_invariants"]))
        self.assertIn("size then lexicographic", " ".join(records["SimplicialCollapse.free-faces"]["required_invariants"]))
        self.assertIn("not a contractibility or collapsibility decision", " ".join(records["SimplicialCollapse.has-free-face"]["required_invariants"]))
        self.assertIn("(Y,B)->(X,A)", " ".join(records["SimplicialCollapse.inclusion"]["required_invariants"]))
        self.assertIn("R i# = identity", " ".join(records["SimplicialCollapse.chain-matrix"]["required_invariants"]))
        self.assertIn("identity - i# R", " ".join(records["SimplicialCollapse.chain-homotopy-matrix"]["required_invariants"]))
        self.assertIn("zero rows", " ".join(records["SimplicialCollapse.cochain-homotopy-matrix"]["required_invariants"]))
        self.assertIn("ILeftProjectionOperation", " ".join(records["SimplicialCollapse.on-chain"]["required_invariants"]))
        self.assertIn("full reduced target pair", " ".join(records["SimplicialCollapse.on-cochain"]["required_invariants"]))
        self.assertIn("positive degree", " ".join(records["SimplicialCollapse.homotopy-on-cochain"]["required_invariants"]))
        self.assertIn("exactly [R_*,i_*]", " ".join(records["SimplicialCollapse.homology-maps"]["required_invariants"]))
        self.assertIn("exactly [R^*,i^*]", " ".join(records["SimplicialCollapse.cohomology-maps"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["SimplicialCollapse.homology-maps"]["known_limitations"]))
        self.assertIn("256-simplex", " ".join(records["SimplicialCollapse.chain-matrices"]["known_limitations"]))
        self.assertIn("empty face is excluded", " ".join(records["SimplicialCollapse.from-absolute-face"]["known_limitations"]))
        self.assertIn("entire subcomplex simplex set", " ".join(records["RelativeMap.is-isomorphic-to"]["required_invariants"]))
        self.assertIn("lexicographically first", " ".join(records["RelativeMap.isomorphism-to"]["required_invariants"]))
        self.assertIn("ICustomResultFlatOperation", " ".join(records["RelativeMap.isomorphisms-to"]["required_invariants"]))
        self.assertIn("1024 maps", " ".join(records["RelativeMap.isomorphisms-to"]["known_limitations"]))
        self.assertIn("Alexander-Whitney", " ".join(records["SimplicialCochain.cup"]["required_invariants"]))
        self.assertIn("not generally graded commutative on cochains", " ".join(records["SimplicialCochain.cup"]["required_invariants"]))
        self.assertIn("H^k(target)->H^k(source)", " ".join(records["SimplicialCochain.cohomology-map"]["required_invariants"]))
        self.assertIn("two cocycles", " ".join(records["SimplicialCochain.cup-class"]["required_invariants"]))
        self.assertIn("noncocycles are undefined", " ".join(records["SimplicialCochain.cohomologous"]["required_invariants"]))
        self.assertIn("empty vector", " ".join(records["SimplicialCochain.cobounding-coordinates"]["required_invariants"]))
        self.assertIn("entire list", " ".join(records["SimplicialCochain.cohomology-degrees"]["required_invariants"]))
        self.assertIn("5000000", " ".join(records["SimplicialCochain.cohomology-maps"]["known_limitations"]))
        self.assertIn("X,A union B", " ".join(records["RelativeCochain.cup"]["required_invariants"]))
        self.assertIn("vanish on every A simplex", " ".join(records["RelativeCochain.from-absolute"]["required_invariants"]))
        self.assertIn("H^(k+1)(X,A)", " ".join(records["RelativeCochain.connecting-cohomology-map"]["required_invariants"]))
        self.assertIn("entire three-map segment", " ".join(records["RelativeCochain.long-exact-segment"]["required_invariants"]))
        self.assertIn("all four maps", " ".join(records["RelativeCochain.long-exact-maps"]["required_invariants"]))
        self.assertIn("H^k(Y,B)->H^k(X,A)", " ".join(records["RelativeCochain.cohomology-map"]["required_invariants"]))
        self.assertIn("filtered before the limit", " ".join(records["RelativeCochain.cohomology-on"]["known_limitations"]))
        self.assertIn("5000000", " ".join(records["RelativeCochain.cohomology-degrees"]["known_limitations"]))

    def test_domain_links_use_exact_domains(self):
        data = copy.deepcopy(self.data)
        next(d for d in data["domains"] if d["id"] == "QxQ.bounds")["supported_operations"].append("Q.add")
        self.assertTrue(any("domain operation participation drift" in x for x in coverage.validate(data)))

    def test_native_sync_is_idempotent_and_preserves_the_survey(self):
        with sync_native_catalog.MANIFEST.open(encoding="utf-8-sig") as source:
            rows = list(csv.DictReader(source, delimiter="\t"))
        result = sync_native_catalog.synchronize(self.data, rows)
        self.assertEqual(self.data, result)
        self.assertEqual(result, sync_native_catalog.synchronize(result, rows))
        historical = copy.deepcopy(self.data)
        old = next(r for r in historical["concepts"] if r.get("runtime_operation_id") == "Z.add")
        old["provenance"]["date"] = "2020-01-01"
        result = sync_native_catalog.synchronize(historical, rows)
        self.assertEqual(old, next(r for r in result["concepts"] if r["id"] == old["id"]))
        old["representation_scope"] = "obsolete scope"
        result = sync_native_catalog.synchronize(historical, rows)
        updated = next(r for r in result["concepts"] if r["id"] == old["id"])
        self.assertEqual(sync_native_catalog.DATE, updated["provenance"]["date"])
        self.assertNotEqual("obsolete scope", updated["representation_scope"])
        reviewed = copy.deepcopy(self.data)
        next(r for r in reviewed["concepts"] if r["id"].startswith("concrete-operation."))["human_review_status"] = "HUMAN_REVIEWED"
        with self.assertRaisesRegex(ValueError, "manual evidence-preserving"):
            sync_native_catalog.synchronize(reviewed, rows)


if __name__ == "__main__":
    unittest.main()
