package operations;

import algebra.concrete.ConcreteMathematics;
import mathematics.foundations.*;
import mathematics.structures.FiniteCategory;
import java.math.BigInteger;
import java.util.*;

/** Small independently specified categories shared by native functor/coherence tests. */
final class FiniteCategoryFixtures {
    private FiniteCategoryFixtures() { }
    static BigInteger n(int value) { return BigInteger.valueOf(value); }
    static Map<BigInteger,BigInteger> map(int... entries) {
        if(entries.length%2!=0) throw new IllegalArgumentException("Expected key/value pairs");
        Map<BigInteger,BigInteger> result=new LinkedHashMap<>();
        for(int i=0;i<entries.length;i+=2) result.put(n(entries[i]),n(entries[i+1]));
        return result;
    }
    static FiniteSet<BigInteger> set(int... values) {
        List<BigInteger> result=new ArrayList<>(); for(int value : values) result.add(n(value));
        return new FiniteSet<>(result);
    }
    static FiniteCategory discrete(int... values) { return FiniteCategory.discrete(set(values)); }
    static FiniteCategory cyclic(int size) {
        int[][] table=new int[size][size];
        for(int i=0;i<size;i++) for(int j=0;j<size;j++) table[i][j]=(i+j)%size;
        return monoid(table,0);
    }
    static FiniteCategory monoid(int[][] table,int identity) {
        Map<BigInteger,Pair<BigInteger,BigInteger>> arrows=new LinkedHashMap<>();
        Map<Pair<BigInteger,BigInteger>,BigInteger> composition=new LinkedHashMap<>();
        for(int i=0;i<table.length;i++) {
            arrows.put(n(i),new Pair<>(n(0),n(0)));
            for(int j=0;j<table.length;j++) composition.put(new Pair<>(n(i),n(j)),n(table[i][j]));
        }
        return new FiniteCategory(set(0),arrows,map(0,identity),composition);
    }
    static FiniteCategory relationCategory(ConcreteMathematics m,boolean indiscrete,int... objects) {
        List<Pair<BigInteger,BigInteger>> pairs=new ArrayList<>();
        for(int i=0;i<objects.length;i++) for(int j=0;j<objects.length;j++)
            if(indiscrete || i<=j) pairs.add(new Pair<>(n(objects[i]),n(objects[j])));
        return FiniteCategory.fromPreorder(new FiniteRelation<>(m.integers.algebra(),m.integers.algebra(),new FiniteSet<>(pairs)));
    }
    /** Full category of canonical sets of sizes 0, 1 and 2, generated by explicit function tables. */
    static FiniteCategory smallSets() {
        Map<BigInteger,Pair<BigInteger,BigInteger>> ends=new TreeMap<>(); List<int[]> functions=new ArrayList<>();
        for(int source=0;source<=2;source++) for(int target=0;target<=2;target++) {
            int count=(int)Math.pow(target,source);
            for(int code=0;code<count;code++) {
                int[] values=new int[source]; int digits=code;
                for(int i=0;i<source;i++) { values[i]=digits%target; digits/=target; }
                ends.put(n(functions.size()),new Pair<>(n(source),n(target))); functions.add(values);
            }
        }
        Map<Pair<BigInteger,BigInteger>,BigInteger> composition=new LinkedHashMap<>();
        for(int first=0;first<functions.size();first++) for(int second=0;second<functions.size();second++)
            if(ends.get(n(first)).second.equals(ends.get(n(second)).first)) {
                int[] values=new int[functions.get(first).length];
                for(int i=0;i<values.length;i++) values[i]=functions.get(second)[functions.get(first)[i]];
                Pair<BigInteger,BigInteger> pair=new Pair<>(ends.get(n(first)).first,ends.get(n(second)).second);
                for(int result=0;result<functions.size();result++) if(ends.get(n(result)).equals(pair) && Arrays.equals(values,functions.get(result)))
                    composition.put(new Pair<>(n(first),n(second)),n(result));
            }
        return new FiniteCategory(set(0,1,2),ends,map(0,0,1,3,2,9),composition);
    }
    static FiniteCategory parallelPair() {
        Map<BigInteger,Pair<BigInteger,BigInteger>> ends=new TreeMap<>();
        ends.put(n(0),new Pair<>(n(0),n(0))); ends.put(n(1),new Pair<>(n(1),n(1)));
        ends.put(n(2),new Pair<>(n(0),n(1))); ends.put(n(3),new Pair<>(n(0),n(1)));
        Map<Pair<BigInteger,BigInteger>,BigInteger> table=new LinkedHashMap<>();
        table.put(new Pair<>(n(0),n(0)),n(0)); table.put(new Pair<>(n(1),n(1)),n(1));
        for(int arrow=2;arrow<=3;arrow++) { table.put(new Pair<>(n(0),n(arrow)),n(arrow)); table.put(new Pair<>(n(arrow),n(1)),n(arrow)); }
        return new FiniteCategory(set(0,1),ends,map(0,0,1,1),table);
    }
}
